from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    MANIFEST_INVALID = "MANIFEST_INVALID"
    MANIFEST_MISSING_FIELD = "MANIFEST_MISSING_FIELD"
    UNKNOWN_PERMISSION = "UNKNOWN_PERMISSION"
    SDK_INCOMPATIBLE = "SDK_INCOMPATIBLE"
    SCHEMA_BREAKING_CHANGE = "SCHEMA_BREAKING_CHANGE"
    ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"
    ARTIFACT_SIGNATURE_INVALID = "ARTIFACT_SIGNATURE_INVALID"
    PACKAGE_VERSION_DIGEST_CONFLICT = "PACKAGE_VERSION_DIGEST_CONFLICT"
    ILLEGAL_STATE_TRANSITION = "ILLEGAL_STATE_TRANSITION"
    PERMISSION_GRANT_REQUIRED = "PERMISSION_GRANT_REQUIRED"
    BINDING_REQUIRED = "BINDING_REQUIRED"
    PACKAGE_NOT_ENABLED = "PACKAGE_NOT_ENABLED"
    PACKAGE_DISABLED = "PACKAGE_DISABLED"
    PACKAGE_REVOKED = "PACKAGE_REVOKED"
    PACKAGE_UNINSTALLED = "PACKAGE_UNINSTALLED"
    ENVIRONMENT_POLICY_VIOLATION = "ENVIRONMENT_POLICY_VIOLATION"
    ADAPTER_UNAVAILABLE = "ADAPTER_UNAVAILABLE"
    INPUT_INVALID = "INPUT_INVALID"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    SLUG_CONFLICT = "SLUG_CONFLICT"
    LAST_OWNER_REQUIRED = "LAST_OWNER_REQUIRED"
    PRINCIPAL_DISABLED = "PRINCIPAL_DISABLED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
    INTERNAL_FAILURE = "INTERNAL_FAILURE"
    ACTION_EXECUTION_DENIED = "ACTION_EXECUTION_DENIED"
    UNKNOWN_PACKAGE_KIND = "UNKNOWN_PACKAGE_KIND"
    UNKNOWN_COMPONENT_KIND = "UNKNOWN_COMPONENT_KIND"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
    DEPENDENCY_VERSION_UNSATISFIED = "DEPENDENCY_VERSION_UNSATISFIED"
    DEPENDENCY_AMBIGUOUS = "DEPENDENCY_AMBIGUOUS"
    DEPENDENCY_CYCLE = "DEPENDENCY_CYCLE"
    DEPENDENCY_CONFLICT = "DEPENDENCY_CONFLICT"
    DEPENDENCY_KIND_MISMATCH = "DEPENDENCY_KIND_MISMATCH"
    DEPENDENCY_CAPABILITY_MISSING = "DEPENDENCY_CAPABILITY_MISSING"
    DEPENDENCY_LAYER_VIOLATION = "DEPENDENCY_LAYER_VIOLATION"
    DEPENDENCY_RESOLUTION_FAILED = "DEPENDENCY_RESOLUTION_FAILED"
    VISIBILITY_VIOLATION = "VISIBILITY_VIOLATION"
    PRIVATE_CONTENT_PUBLICATION_DENIED = "PRIVATE_CONTENT_PUBLICATION_DENIED"
    NAMESPACE_CONFLICT = "NAMESPACE_CONFLICT"
    CAPABILITY_CONFLICT = "CAPABILITY_CONFLICT"
    SCENARIO_DOMAIN_CAPABILITY_MISSING = "SCENARIO_DOMAIN_CAPABILITY_MISSING"
    OVERLAY_TARGET_MISSING = "OVERLAY_TARGET_MISSING"
    PERMISSION_EXPANSION = "PERMISSION_EXPANSION"
    RESOURCE_BUDGET_EXPANSION = "RESOURCE_BUDGET_EXPANSION"
    PLATFORM_INCOMPATIBLE = "PLATFORM_INCOMPATIBLE"
    FDS_INCOMPATIBLE = "FDS_INCOMPATIBLE"
    EXECUTABLE_BOUNDARY_REQUIRED = "EXECUTABLE_BOUNDARY_REQUIRED"
    LOCK_DIGEST_MISMATCH = "LOCK_DIGEST_MISMATCH"
    LOCK_CONTENT_MISMATCH = "LOCK_CONTENT_MISMATCH"
    REGISTRY_VERSION_NOT_FOUND = "REGISTRY_VERSION_NOT_FOUND"
    REGISTRY_STATE_UNAVAILABLE = "REGISTRY_STATE_UNAVAILABLE"
    ORGANIZATION_SCOPE_MISMATCH = "ORGANIZATION_SCOPE_MISMATCH"
    INSTALLATION_STATE_INVALID = "INSTALLATION_STATE_INVALID"
    PROJECT_NOT_ACTIVE = "PROJECT_NOT_ACTIVE"
    PROJECT_ORGANIZATION_MISMATCH = "PROJECT_ORGANIZATION_MISMATCH"
    CURRENT_DOMAIN_LOCK_CONFLICT = "CURRENT_DOMAIN_LOCK_CONFLICT"
    WITHDRAWN_OR_QUARANTINED_DEPENDENCY = "WITHDRAWN_OR_QUARANTINED_DEPENDENCY"
    UNINSTALL_BLOCKED_BY_CURRENT_LOCK = "UNINSTALL_BLOCKED_BY_CURRENT_LOCK"


class ForgeOpsError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        details: dict[str, Any] | None = None,
        http_status: int = 400,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}
        self.http_status = http_status

    def as_dict(self) -> dict[str, Any]:
        return {"code": self.code.value, "message": self.message, "details": self.details}
