from __future__ import annotations

from typing import Protocol
from uuid import UUID

from forgeops.platform_core.identity_access.entities import (
    BindingState,
    Membership,
    Organization,
    Principal,
    Project,
    ProjectPackageBinding,
    ScopeType,
    Workspace,
)


class IdentityRepository(Protocol):
    def get_principal_by_subject(self, subject_ref: str) -> Principal | None: ...

    def get_principal(self, principal_id: UUID) -> Principal | None: ...

    def list_memberships_for_principal(self, principal_id: UUID) -> tuple[Membership, ...]: ...

    def list_memberships_for_organization(
        self, organization_id: UUID
    ) -> tuple[Membership, ...]: ...

    def get_membership(self, membership_id: UUID) -> Membership | None: ...

    def add_membership(self, membership: Membership, idempotency_key: str) -> Membership: ...

    def save_membership(self, membership: Membership, expected_version: int) -> Membership: ...

    def count_active_org_owners(self, organization_id: UUID) -> int: ...

    def list_organizations(self) -> tuple[Organization, ...]: ...

    def get_organization(self, organization_id: UUID) -> Organization | None: ...

    def add_organization_with_owner(
        self,
        organization: Organization,
        owner: Membership,
        idempotency_key: str,
    ) -> Organization: ...

    def save_organization(
        self, organization: Organization, expected_version: int
    ) -> Organization: ...

    def list_workspaces(self, organization_id: UUID) -> tuple[Workspace, ...]: ...

    def get_workspace(self, workspace_id: UUID) -> Workspace | None: ...

    def add_workspace(self, workspace: Workspace, idempotency_key: str) -> Workspace: ...

    def save_workspace(self, workspace: Workspace, expected_version: int) -> Workspace: ...

    def list_projects(self, workspace_id: UUID) -> tuple[Project, ...]: ...

    def get_project(self, project_id: UUID) -> Project | None: ...

    def add_project(self, project: Project, idempotency_key: str) -> Project: ...

    def save_project(self, project: Project, expected_version: int) -> Project: ...

    def get_binding(self, binding_id: UUID) -> ProjectPackageBinding | None: ...

    def get_project_installation_binding(
        self, project_id: UUID, installation_id: UUID
    ) -> ProjectPackageBinding | None: ...

    def list_project_bindings(self, project_id: UUID) -> tuple[ProjectPackageBinding, ...]: ...

    def add_project_binding(
        self, binding: ProjectPackageBinding, idempotency_key: str
    ) -> ProjectPackageBinding: ...

    def save_project_binding(
        self, binding: ProjectPackageBinding, expected_version: int
    ) -> ProjectPackageBinding: ...

    def find_idempotent_resource(
        self, actor_ref: str, operation: str, idempotency_key: str
    ) -> tuple[str, UUID] | None: ...

    def organization_id_for_scope(self, scope_type: ScopeType, scope_id: UUID) -> UUID | None: ...

    def binding_state_for_installation(
        self, project_id: UUID, installation_id: UUID
    ) -> BindingState | None: ...
